//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto_УслугиМатериалы
    {
        public int id { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<int> id_uslugi { get; set; }
        public Nullable<int> kolvo_zakaz { get; set; }
    
        public virtual Auto_Материал Auto_Материал { get; set; }
        public virtual Auto_Услуги Auto_Услуги { get; set; }
    }
}
