//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto_Заказ
    {
        public int id { get; set; }
        public Nullable<int> id_uslugi { get; set; }
        public Nullable<System.DateTime> date_order { get; set; }
        public Nullable<int> id_status { get; set; }
        public string comment { get; set; }
        public Nullable<int> id_worker { get; set; }
        public Nullable<int> id_car { get; set; }
    
        public virtual Auto_Машина Auto_Машина { get; set; }
        public virtual Auto_Сотрудники Auto_Сотрудники { get; set; }
        public virtual Auto_СтатусЗаказа Auto_СтатусЗаказа { get; set; }
        public virtual Auto_Услуги Auto_Услуги { get; set; }
    }
}
